spring.application.name=users-service
server.port=8082

# Datasource (PostgreSQL)
spring.datasource.url=${USERS_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true