spring.application.name=orders-service
server.port=8084

# Datasource (PostgreSQL)
spring.datasource.url=${ORDERS_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
