spring.application.name=batch-service
server.port=8090

# Database configuration
spring.datasource.url=${USERS_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Spring Batch settings
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
spring.batch.job.name=importUsersJob

spring.jpa.open-in-view=false
logging.level.org.springframework.batch=INFO


